name: Create PR to Release Branch on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  create_pr_to_release_branch:
    runs-on: ubuntu-latest
    name: Create PR into Branch from Label
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.label.name, 'release-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cherry Pick into Release Branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: ${{ github.event.label.name }}
          force: true
